pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        //maven { url '\\\\192.168.10.93\\smb\\OctopusFrameworkLibs'}
        maven { url 'E:\\\\Android-Projects\\\\OpenAndroidFrameworkToolkitsLibs'}
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        //maven { url '\\\\192.168.10.93\\smb\\OctopusFrameworkLibs'}
        maven { url 'E:\\\\Android-Projects\\\\OpenAndroidFrameworkToolkitsLibs'}
    }
}

rootProject.name = "AndroidVehicleMiddleServicesToolkits"
include ':app'
